version: "3"

volumes:
  node1_storage:
  node2_storage:
  node3_storage:



services:
  node1:
    container_name: node1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #オーバーライドするファイルを指定
        CONFIGFILE: node1_broker.xml
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - 8081:8161
    volumes:
      - node1_storage:/var/lib/artemis-instance

  node2:
    container_name: node2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #オーバーライドするファイルを指定
        CONFIGFILE: node2_broker.xml
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - 8082:8161
    volumes:
      - node2_storage:/var/lib/artemis-instance

  node3:
    container_name: node3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #オーバーライドするファイルを指定
        CONFIGFILE: node3_broker.xml
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - 8083:8161
    volumes:
      - node3_storage:/var/lib/artemis-instance

